image:
  repository: pushpakumara/kubepulse-backend
  tag: "1.0.0"

django:
  replicas: 1
  port: 8000

postgres:
  db: kubepulse_db
  user: postgres_user
  password: postgres_password
  storage: 10Gi

redis:
  enabled: true
  image: redis:7-alpine
  port: 6379
  serviceName: redis

frontend:
  image:
    repository: pushpakumara/kubepulse-frontend
    tag: "1.0.0"

ingress:
  enabled: false
  frontendHost: stg.frontend.kubepulse.local
  backendHost: stg.api.kubepulse.local
